param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot/../..")
)

$instructionsDir        = Join-Path $RepoRoot ".github/instructions"
$copilotInstructionsPath = Join-Path $RepoRoot ".github/copilot-instructions.md"
$agentsPath             = Join-Path $RepoRoot "AGENTS.md"

# Map each instructions file to a section in AGENTS.md
$sections = @(
    @{
        Key      = "general-code-change"
        Title    = "General Code Change Policy"
        FileName = "general-code-change.instructions.md"
    },
    @{
        Key      = "general-unit-test"
        Title    = "General Unit Test Policy"
        FileName = "general-unit-test.instructions.md"
    },
    @{
        Key      = "github-actions"
        Title    = "GitHub Actions Workflow Policy"
        FileName = "github-actions.instructions.md"
    },
    @{
        Key      = "python-code-change"
        Title    = "Python Code Change Policy"
        FileName = "python-code-change.instructions.md"
    },
    @{
        Key      = "python-unit-test"
        Title    = "Python Unit Test Policy"
        FileName = "python-unit-test.instructions.md"
    },
    @{
        Key      = "powershell-code-change"
        Title    = "PowerShell Code Change Policy"
        FileName = "powershell-code-change.instructions.md"
    },
    @{
        Key      = "powershell-unit-test"
        Title    = "PowerShell Unit Test Policy"
        FileName = "powershell-unit-test.instructions.md"
    }
)

function Get-InstructionsBody {
    param(
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Instructions file not found: $Path"
    }

    $content = Get-Content -Raw -LiteralPath $Path

    # Strip YAML frontmatter if present (between leading --- lines)
    if ($content -match '^\s*---\s*[\s\S]*?---\s*') {
        $content = $content -replace '^\s*---\s*[\s\S]*?---\s*', ''
    }

    return $content.Trim()
}

# 1. Copilot repo-wide instructions (go first in AGENTS.md)
$copilotBody = Get-InstructionsBody -Path $copilotInstructionsPath

$copilotSection = @"
## Repository Instructions (GitHub Copilot Canonical)

<!-- BEGIN: copilot-instructions -->
$copilotBody

<!-- END: copilot-instructions -->

"@

# 2. Section blocks from .github/instructions/*.instructions.md
$sectionBlocks = foreach ($section in $sections) {
    $filePath = Join-Path $instructionsDir $section.FileName
    $body     = Get-InstructionsBody -Path $filePath

    @"
## $($section.Title)

<!-- BEGIN: $($section.Key) -->
$body

<!-- END: $($section.Key) -->

"@
}

# 3. Header for AGENTS.md
$header = @"
# AGENTS.md

> NOTE: This file is **generated** from:
>
> - .github/copilot-instructions.md
> - .github/instructions/general-code-change.instructions.md
> - .github/instructions/general-unit-test.instructions.md
> - .github/instructions/github-actions.instructions.md
> - .github/instructions/python-code-change.instructions.md
> - .github/instructions/python-unit-test.instructions.md
> - .github/instructions/powershell-code-change.instructions.md
> - .github/instructions/powershell-unit-test.instructions.md
>
> Do not edit this file manually.
> To update policies, edit the source *.instructions.md files and
> `.github/copilot-instructions.md`, then run:
>
>   pwsh -File scripts/dev-tools/sync-agents-from-instructions.ps1

## Repository Setup (High-Level)

- For coding and testing policies, always follow the sections below in the order:
  Copilot instructions → general policies → language-specific policies → CI policies.
- Use the language- and domain-specific sections for Python, PowerShell, and CI behavior.
"@

# 4. Assemble final AGENTS.md content:
#    header → copilot section → all other sections
$agentsContent = $header + "`n`n" + $copilotSection + "`n" + ($sectionBlocks -join "`n")

Set-Content -LiteralPath $agentsPath -Value $agentsContent -NoNewline
Write-Host "Updated $agentsPath from .github/copilot-instructions.md and .github/instructions/*.instructions.md"