from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, List, Set

import requests

API_URL = "https://gutendex.com/books"


def fetch_ids(
    languages: Iterable[str],
    english_only: bool,
) -> List[int]:
    normalized_langs = sorted({lang.strip().lower() for lang in languages if lang})
    if not normalized_langs:
        raise ValueError("At least one language must be provided.")

    params = {"languages": ",".join(normalized_langs)}
    results: Set[int] = set()
    url: str | None = API_URL

    while url:
        response = requests.get(url, params=params, timeout=60)
        response.raise_for_status()
        payload = response.json()
        for entry in payload.get("results", []):
            entry_langs = [code.lower() for code in entry.get("languages", [])]
            if english_only and set(entry_langs) != {"en"}:
                continue
            if any(lang in normalized_langs for lang in entry_langs):
                entry_id = entry.get("id")
                if isinstance(entry_id, int):
                    results.add(entry_id)
        url = payload.get("next")
        params = None

    return sorted(results)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate data/meta/gutenberg_ids.txt from Gutendex."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/meta/gutenberg_ids.txt"),
        help="Where to write the ID list.",
    )
    parser.add_argument(
        "--languages",
        nargs="+",
        default=["en"],
        help="Gutendex language codes to include (default: en).",
    )
    parser.add_argument(
        "--allow-multi-language",
        action="store_true",
        help="Include works that list additional languages besides English.",
    )
    args = parser.parse_args()

    try:
        ids = fetch_ids(args.languages, english_only=not args.allow_multi_language)
    except Exception as exc:  # pragma: no cover - CLI surface
        print(f"Failed to fetch Gutenberg IDs: {exc}", file=sys.stderr)
        sys.exit(1)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    header_parts = [
        "Autogenerated from Gutendex",
        f"Languages: {', '.join(args.languages)}",
    ]
    if not args.allow_multi_language:
        header_parts.append("Filtered to strictly English entries")
    header = "# " + " | ".join(header_parts) + "\n"
    with args.output.open("w", encoding="utf-8") as fh:
        fh.write(header)
        for ebook_id in ids:
            fh.write(f"{ebook_id}\n")

    print(f"Wrote {len(ids)} Gutenberg IDs to {args.output}")


if __name__ == "__main__":
    main()
